---
###############################
# single chapter knit options #
###############################
output:
  bookdown::pdf_document2:
    template: templates/brief_template.tex
    citation_package: biblatex
  bookdown::html_document2: default
  bookdown::word_document2: default
documentclass: book
bibliography: [bibliography/references.bib]
#chapter level bibliography
#bibliography: [bibliography/intro-ref.bib]
params:
  width: 70%
---

# Anthropogenic marine debris as habitat and pathway for range shifts and the introduction of invasive species
\chaptermark{AMD as habitat and pathway}

```{block type='savequote', include=knitr::is_latex_output(), quote_author='(ref:leguin-quote)'}
You can see the old cities, still everywhere, the bones and bricks go to dust, but the little pieces of plastic never do. They never adapt either.
```
(ref:leguin-quote) --- Ursula K. LeGuin, _The Dispossessed_

## Introduction

Plastic pollution is altering marine ecosystems [@citekey; @citekey]. The growing mass of plastic, fishing gear, synthetic clothing, and other artifacts of the Anthropocene [@citekey] break down slowly and accumulate at the surface and seafloor of every ocean on Earth. This anthropogenic marine debris (AMD) represents a large and growing proportion of the floating material [@Koelmans2017] that can be used by plants, animals, and other organisms as habitat [@citekey] and a mode of travel [@citekey]. While AMD does not adapt to its surroundings, life does adapt to and around it [@citekey]. These co-occuring organisms, known as neuston, are adapted to life within the dynamic boundary layer of water and air and the unique challenges it presents to their physiology. Neuston survive an environment with extreme fluctuations of temperature, salinity, and nutrient availability. The addition of anthropogenic marine debris (AMD) to this unique environment presents a significant shift in the availability of solid substrate, a previously limiting resource, and may therefore initiate shifts in both how it functions and interacts with the rest of the ocean.

## Characteristics of anthropogenic marine debris

These tonnes of buoyant AMD include single-use items and fishing gear, along with a mixture of other plastics, rubber, petroleum-based cloth and fibres, metal, and engineered wood products (Gönülal et al., 2016; Hong et al., 2014; Lavers et al., 2019). The majority of this material is fragments, fibres, and pellets larger than 5mm at its longest dimension, collectively known as macrodebris (Koelmans et al., 2017). Most floating anthropogenic macrodebris is resistant to structural degradation over long time-frames (O’Brine & Thompson, 2010) and may therefore be capable of traversing vast oceanic distances intact (Pearce, Jackson, & Cresswell, 2018).

### Anthropogenic marine debris is a growing pollutant

Numerous studies have shown AMD's capacity to function and their consumers in the top layer of the world’s oceans (Goldstein, Carson, & Eriksen, 2014; Hoeksema, Roos, & Cadée, 2012; McCuller & Carlton, 2018). Studies consistently find that most of this debris is composed of petroleum-based synthetic materials  (Gönülal, Öz, Güreşen, & Öztürk, 2016; Hong, Lee, Kang, Choi, & Ko, 2014; Lavers, Dicks, Dicks, & Finger, 2019; Santos, Friedrich, & Ivar do Sul, 2009). In 2018, approximately 357 Mt of these synthetics were produced globally (PlasticsEurope, 2019). Much of this production will be recycled or recaptured for energy production. However, the amount of plastic which bypasses these fates and deposits in landfills or the natural environment is projected to reach 12,000 Mt by 2050 (Geyer, Jambeck, & Law, 2017). 

### Sources and sinks

Text.

### Types and categorisation methods

Text.

### Scope of impacts on human and natural systems

Text.

## Anthropogenic marine debris as habitat

Text.

### A brief history of man’s battle with fouling

Text.

### A material comparison of anthropogenic and natural debris

Text.

### Successional patterns on AMD

Text.

### AMD as habitat for motile organisms

Text.

### Habitat connectivity in the epipelagic

Text.

## Rafting aboard anthropogenic marine debris

Text.

### Natural history and biogeography

Text.

### Mechanisms of rafting

Text.

### Comparing AMD and natural debris as rafting substrate

Text.

### Rafting in the age of climate change

Text.

### Japanese Tsunami Debris

Text.

## Marine biosecurity history and practice

Text.

### Classifying species by location and harm

Text.

### Natural and human-mediated range expansions

Text.

### Recognising risk and harm

Text.

### Prevention and response efforts

Text.

### Contemporary views on AMD as a biosecurity pathway

Text.

## Thesis overview

Text.

### Aims and objectives

Text.

### Navigating the structure

Text.

### Key terminology

Text.


