---
#########################################
# options for knitting a single chapter #
#########################################
output:
  bookdown::pdf_document2:
    template: templates/brief_template.tex
    citation_package: biblatex
  bookdown::html_document2: default
  bookdown::word_document2: default
documentclass: book
bibliography: [bibliography/references.bib]
#chapter level bibliography
#bibliography: [bibliography/synth-ref.bib]
params:
  width: 70%
---

# Organisms associated with anthropogenic marine debris reported in the scientific literature globally from 1990 to 2019
\chaptermark{OAAMD Database}

```{r setup, include = F, }
library(tidyverse)
library(janitor)
library(purrr)

file_location <- '~/PhD/thesis_git/mac-thesis/data/biosec/'
```


```{r load files, include = F, }

pull_dfs <- c("organisms", "papers", "spatial", "taxonomy")
file_type <- c(".csv")

list_dfs <- pull_dfs %>%
  map(~ read.csv(paste0(file_location, ., file_type), encoding = "UTF-8")) %>%
  map(~ na_if(., "")) %>%
  map(~ remove_empty(., which = c("rows", "cols"))) %>%
  map(~ janitor::clean_names(.)) %>%
  map(~ rename_with(., ~str_remove(., "x_u_feff_")))
  
names(list_dfs) <- pull_dfs

list2env(list_dfs, envir = globalenv())

organisms_clean <- organisms %>%
  select(-rank) %>%
  mutate(scientific_name = fct_recode(as.factor(scientific_name),
                                      Actiniaria = "Actinaria",
                                      Amoebophrya = "Amoebophyra"))
#names need further cleaning

df_orgs <- left_join(organisms_clean, taxonomy)

```

```{r manual table creation, include = F}



```

## Abstract

Text.

## Introduction

Text.

## Methods

Text.

## Results

Text.

## Discussion

Text.